version: "3"

services:
  appdb:
    image: postgres
    container_name: appdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_DB=app
    volumes:
      - ./appdata:/data
  testdb:
    image: postgres
    container_name: testdb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_DB=test
    volumes:
      - ./testdata:/data
